
simplecov:
  stage: test
  image: docker.io/rails:5
  script:
    - bunlde install
    - rails test
  artifacts:
    paths:
      - coverage/
  variables:
    GIT_SSL_NO_VERIFY: "true"

pages:
  stage: deploy
  dependencies:
    - simplecov
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
