
simplecov:
  stage: test
  image: docker.io/ruby:2.5.1
  script:
    - gem install rails -v 5.1.6
    - gem install bundler
    - bundle install
    - rails test
  artifacts:
    paths:
      - coverage/
  variables:
    GIT_SSL_NO_VERIFY: "true"
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - simplecov
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
