
simplecov:
  stage: test
  image: krismichalski/docker-rails:2.4
  script:
    - gem install bundler
    - bundle install --gemfile=Gemfile
    - rails db:migrate
    - rails test
  artifacts:
    paths:
      - coverage/
  variables:
    GIT_SSL_NO_VERIFY: "true"
  # only:
  #   - master

