
simplecov:
  stage: test
  image: docker.io/ruby:2.5.1
  script:
    - gem install rails -v 5.1.6
    - gem install bundler
    - bundle install --gemfile=Gemfile
    - rails db:migrate
    - rails test
  artifacts:
    paths:
      - coverage/
  variables:
    GIT_SSL_NO_VERIFY: "true"
  only:
    - master

